import os
import re
import logging
from sgd import app, home
from sgd import tenancy
from sgd.meta import MetadataNotFound, Meta
from sgd.streams import Streams
from sgd.utils import split_stream_id, hr_size
from json import dumps
from flask import g, jsonify, abort, Response, redirect, request
from datetime import datetime

logger = logging.getLogger(__name__)

# tt1234567 for IMDb ids, or tmdb:1234 for TMDB ids, optionally followed by
# :<season>:<episode> for series.
VALID_IMDB_ID = re.compile(r"^tt\d{5,10}$", re.IGNORECASE)
VALID_SEASON_EPISODE = re.compile(r"^\d+$")

# UUID as generated by Postgres' gen_random_uuid() / RFC 4122.
VALID_USER_ID = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)


def is_valid_stream_id(stream_id):
    parts = split_stream_id(stream_id)
    base_id = parts[0].lower()

    if base_id == "tmdb":
        if len(parts) < 2 or not parts[1].isdigit():
            return False
        extra = parts[2:]
    elif VALID_IMDB_ID.match(base_id):
        extra = parts[1:]
    else:
        return False

    return len(extra) <= 2 and all(VALID_SEASON_EPISODE.match(p) for p in extra)


BASE_MANIFEST = {
    "id": "streamhelium.stremio.googledrive",
    "version": "1.1.5",
    "name": "Stream Helium",
    "description": "Este plugin busca Filmes e Séries.",
    "favicon": "https://catalogo.heliummarcos.com.br/addon/favicon.png",
    "logo": "https://catalogo.heliummarcos.com.br/addon/logo2.png",
    "background": "https://catalogo.heliummarcos.com.br/addon/background2.png",
    "resources": ["stream"],
    "types": ["movie", "series"],
    "catalogs": [],
}

# Alias kept for backward compatibility with existing tests/imports.
MANIFEST = BASE_MANIFEST


def manifest_for(user_row):
    manifest = dict(BASE_MANIFEST)
    # Distinct addon id per user so multiple accounts can be installed
    # side by side in the same Stremio app without colliding.
    manifest["id"] = f"{BASE_MANIFEST['id']}.{user_row['id']}"
    if user_row.get("display_name"):
        manifest["name"] = f"{BASE_MANIFEST['name']} - {user_row['display_name']}"
    return manifest


def manifest_url(user_id):
    """Vercel terminates TLS in front of the app, so request.url_root comes
    through as http:// - force https so the link we hand to Stremio works."""
    return f"https://{request.host}/u/{user_id}/manifest.json"


@app.before_request
def _load_tenant_if_scoped():
    """Runs before every request; only does work for /u/<user_id>/... URLs.
    Rejects malformed ids early so they never reach a DB lookup."""
    user_id = request.view_args.get("user_id") if request.view_args else None
    if user_id is None:
        return
    if not VALID_USER_ID.match(user_id):
        abort(404)
    tenancy.load_tenant(user_id)


@app.route("/")
def init():
    page = home.render_landing()
    resp = Response(page, mimetype="text/html; charset=utf-8")
    resp.headers["X-Robots-Tag"] = "noindex"
    return resp


def mask_email(email):
    """h****s@gmail.com - the page is public, the owner's address isn't."""
    if not email or "@" not in email:
        return email or ""
    user, _, domain = email.partition("@")
    if len(user) <= 2:
        return f"{user[0]}*@{domain}"
    return f"{user[0]}{'*' * (len(user) - 2)}{user[-1]}@{domain}"


def drive_status():
    """A cheap liveness check against the Drive API for the user's landing page."""
    try:
        about = (
            g.gdrive.drive_instance.about()
            .get(fields="user(displayName,emailAddress),storageQuota")
            .execute()
        )
    except Exception as e:
        logger.warning("Drive health check failed: %s", e)
        return {"connected": False, "error": type(e).__name__}

    user = about.get("user", {})
    quota = about.get("storageQuota", {})
    status = {
        "connected": True,
        "account": mask_email(user.get("emailAddress")) or user.get("displayName"),
    }

    try:
        usage = int(quota.get("usage", 0))
        status["usage_human"] = hr_size(usage)
        limit = quota.get("limit")
        if limit:
            limit = int(limit)
            status["limit_human"] = hr_size(limit)
            status["usage_pct"] = round(usage / limit * 100, 1) if limit else None
    except (TypeError, ValueError):
        pass

    return status


@app.route("/health")
def health():
    """Service-level health check (no specific user in scope)."""
    from sgd import db
    try:
        with db.get_conn() as conn:
            conn.execute("SELECT 1")
        db_ok = True
    except Exception as e:
        logger.warning("DB health check failed: %s", e)
        db_ok = False

    resp = jsonify({"status": "ok" if db_ok else "degraded", "db": db_ok})
    resp.status_code = 200 if db_ok else 503
    return resp


@app.route("/u/<user_id>/health")
def user_health(user_id):
    status = drive_status()
    payload = {
        "status": "ok" if status.get("connected") else "degraded",
        "addon": {
            "id": manifest_for(g.user)["id"],
            "name": manifest_for(g.user)["name"],
            "manifest": manifest_url(user_id),
        },
        "drive": status,
        "config": {"tmdb": bool(g.tmdb_api_key)},
    }
    resp = jsonify(payload)
    resp.status_code = 200 if status.get("connected") else 503
    return common_headers(resp)


@app.route("/favicon.png")
@app.route("/favicon.ico")
def favicon():
    return redirect(BASE_MANIFEST["favicon"], code=302)


@app.route("/u/<user_id>/")
def user_landing(user_id):
    page = home.render(
        manifest=manifest_for(g.user),
        manifest_url=manifest_url(user_id),
        stremio_url=f"stremio://{request.host}/u/{user_id}/manifest.json",
        tmdb_enabled=bool(g.tmdb_api_key),
        proxy_enabled=bool(os.environ.get("CF_PROXY_URL")),
    )
    resp = Response(page, mimetype="text/html; charset=utf-8")
    resp.headers["X-Robots-Tag"] = "noindex"
    return resp


@app.route("/u/<user_id>/manifest.json")
def addon_manifest(user_id):
    return common_headers(jsonify(manifest_for(g.user)))


@app.route("/u/<user_id>/stream/<stream_type>/<stream_id>.json")
def addon_stream(user_id, stream_type, stream_id):
    invalid_stream_type = stream_type not in BASE_MANIFEST["types"]
    invalid_id = not is_valid_stream_id(stream_id)

    if invalid_stream_type or invalid_id:
        abort(404)
    try:
        resp = Response(
            response=get_streams(g.gdrive, stream_type, stream_id),
            mimetype="application/json",
        )
        return common_headers(resp)
    except MetadataNotFound as e:
        logger.info("%s", e)
        abort(404)


def common_headers(resp_obj):
    resp_obj.headers["Access-Control-Allow-Origin"] = "*"
    resp_obj.headers["Access-Control-Allow-Headers"] = "*"
    resp_obj.headers["X-Robots-Tag"] = "noindex"
    return resp_obj


def get_streams(gdrive, stream_type, stream_id):
    # Stream the response body so the connection stays open (and doesn't hit
    # a request timeout) while we search Drive and score the results.
    yield '{"streams":'

    start_time = datetime.now()
    time_taken = lambda st: f"{(datetime.now() - st).total_seconds():.3f}s"

    stream_meta = Meta(stream_type, stream_id)
    gdrive.search(stream_meta)
    logger.info(
        "Got %d/%d unique results from gdrive after deduping in %s. Scoring results...",
        len(gdrive.results), gdrive.len_response, time_taken(start_time),
    )
    streams = Streams(gdrive, stream_meta)
    logger.info(
        "Fetched %d/%d valid stream(s) in %s for %s -> %s",
        len(streams.results), len(gdrive.results), time_taken(start_time),
        stream_id, gdrive.query,
    )

    yield f"{dumps(streams.results)}}}"
